apiVersion: apps/v1
kind: Deployment
metadata:
  name: golangapp-deployment
  labels:
    app: golangapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: golangapp
  template:
    metadata:
      labels:
        app: golangapp
    spec:
      containers:
      - name: golangapp
        image: golangapp:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: golangapp-service
  labels:
    service: golangapp
spec:
  type: NodePort
  selector:
    app: golangapp
  ports:
  - port: 8000
    targetPort: 8000